app/main.py
from flask import render_template, Blueprint

bp = Blueprint('main', __name__)

@bp.route('/')
def landing_page():
    """ Logic before  register and login """
    return render_template('landing.html')

@bp.route('/about_section')
def about_section():
    """ Route to display the about section"""
    return render_template('about_section.html')





    

app/templates/about_section.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
      <ul class="nav nav-pills justify-content-end ml-auto">
        <li class="active">
          <form action="{{ url_for('main.landing_page') }}">
            <button type="submit" class="btn btn-primary">Back</button>
          </form>
        </li>
        <li class="active">
          <form action="{{ url_for('users.login') }}">
            <button type="submit" class="btn btn-primary">Sign In</button>
          </form>
        </li>
        <li class="active">
          <form action="{{ url_for('users.register') }}">
            <button type="submit" class="btn btn-primary">Sign Up</button>
          </form>
        </li>
      </ul>
</div>
<div class="container" style="font-style: italic;">
  <div class="row">
    <div class="col-md-8 offset-md-2  ">
      <h3 class="text-center">About SkillJourney</h3>
      <p class="small-text">SkillJourney is like a cozy corner on the internet where people from all over gather to learn cool stuff and chat with each other. It's my special project for Holberton, kind of like my online portfolio.</p>
      
      <p class="small-text">I got the idea from a website I love called MyDrama List (MDL), where folks share their favorite Asian dramas and chat about them. I thought, "Hey, why not do something like this but for learning new skills?"</p>
      
      <p class="small-text">So, I created SkillJourney! Here, you can find all sorts of resources to help you learn new things or get better at stuff you already know. It's like a treasure trove of knowledge waiting for you to explore.</p>
      
      <p class="small-text">But the best part? You're not alone on this journey! SkillJourney has a friendly community where you can leave comments, share useful links, and chat with other learners just like you.</p>
      
      <p class="small-text">Whether you want to dive into coding, get creative with graphic design, or even learn how to make the perfect cup of coffee, SkillJourney is here to help you every step of the way. So, what are you waiting for? Let's embark on this exciting learning adventure together!</p>
      
      <div class="mt-4">
        <h5>Connect with us:</h5>
        <ul class="list-unstyled">
          <li><a href="https://www.instagram.com/edith.gleam/">Instagram</a></li>
          <li><a href="https://www.facebook.com/edith.banda.31105?mibextid=ZbWKwL">Facebook</a></li>
          <li><a href="https://github.com/faith2221">GitHub</a></li>
          <li><a href="https://x.com/edith_serenity?t=xoWZMBHZ7pvU2JswKYJpNw&s=09">Twitter</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/landing.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
      <ul class="nav nav-pills justify-content-end ml-auto">
        <li class="active">
          <form action="{{ url_for('users.home') }}">
            <button type="submit" class="btn btn-primary">Home</button>
          </form>
        </li>
        <li class="active">
          <form action="{{ url_for('users.login') }}">
            <button type="submit" class="btn btn-primary">Sign In</button>
          </form>
        </li>
        <li class="active">
          <form action="{{ url_for('users.register') }}">
            <button type="submit" class="btn btn-primary">Sign Up</button>
          </form>
        </li>
      </ul>
</div>
<div class="container text-center" style="font-style: italic;">
  <h1 style="margin-bottom: 20px; color: white";>Features</h1>
  <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
     <img src="{{ url_for('static', filename='images/gif/registration.gif') }}" alt="registration" style="width: 20%; height: 20%;">
       <p>Join us today by registering and become a valued member of our vibrant community.</p>
     <img src="{{ url_for ('static', filename='images/gif/settings.gif') }}" alt="settings" style="width: 20%; height: 20%;">
       <p>Personalize your experience by configuring your desired setting</p>
     <img src="{{ url_for('static', filename='images/gif/media.gif') }}" alt="media" style="width: 20%; height: 20%;">
       <p>Connect with peers, share insights, and collaborate on your skill-building journey.</p>
  </div>
</div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SkillJourney</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
     crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='layout.css') }}">
  </head>
  <body>
    <header>
        <span class="logo">
             <span class="logo-text-big">SkillJourney</span>
             <span class="slogan">SJ</span>
        </span>
    </header>
    {% include "inc/message.html" %}
    {% block content %} {% endblock content %}
    <footer>
      <div class="footer">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <p class="text-center"><a href="{{ url_for('main.about_section') }}">About Section</a></p>
              <p class="text-center">Copyright &copy; 2024 SkillJourney </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
     integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"></script>
  </body>
</html>